name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Main Site
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.61.243.140
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /root/deploy-main.sh

  deploy-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Admin Site
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.61.243.140
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /root/deploy-admin.sh
